# Настройки окна
WINDOW_WIDTH = 1152
WINDOW_HEIGHT = 648
WINDOW_TITLE = "Duel Game"

# Настройки игрока
PLAYER_SPEED = 5
PLAYER_HEALTH = 100
PLAYER_JUMP_HEIGHT = 1
PLAYER_GRAVITY = 0.5

# Настройки противника
ENEMY_SPEED = 2
ENEMY_HEALTH = 100
ENEMY_DODGE_CHANCE = 0.3  # Шанс уклонения

# Настройки оружия
ATTACK_RANGE = 2
ATTACK_DAMAGE = 10
WEAPON_SCALE = (0.5, 0.5, 2)
WEAPON_POSITION = (0.5, -0.5, 1)
WEAPON_ROTATION = (0, 0, 45)

# Настройки анимаций
ATTACK_DURATION = 0.1
BLOCK_DURATION = 0.1
